// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFFmpegInstalled():Promise<boolean>;

export function Cleanup():Promise<void>;

export function ClearAudioCache():Promise<void>;

export function GetAppInfo():Promise<Record<string, string>>;

export function GetCacheInfo():Promise<Record<string, any>>;

export function GetCoverServerInfo():Promise<Record<string, any>>;

export function GetDiscordRPCStatus():Promise<Record<string, any>>;

export function GetPlaylists():Promise<Array<main.Playlist>>;

export function GetSettings():Promise<main.Settings>;

export function GetSongFile(arg1:string):Promise<string>;

export function GetSongFileURL(arg1:string,arg2:boolean,arg3:boolean):Promise<string>;

export function GetStaticFolderPath():Promise<string>;

export function NotifyPlaybackState(arg1:main.Song,arg2:boolean):Promise<void>;

export function ResetSettings():Promise<void>;

export function ScanPlaylistFiles(arg1:string):Promise<Record<string, Array<string>>>;

export function SetCurrentSong(arg1:main.Song,arg2:boolean):Promise<void>;

export function TestDiscordRPC():Promise<Record<string, any>>;

export function UpdateDiscordPresence(arg1:main.Song,arg2:boolean):Promise<void>;

export function UpdateDiscordPresenceWithPosition(arg1:number):Promise<void>;

export function UpdatePlaybackPosition(arg1:number):Promise<void>;

export function UpdateSettings(arg1:main.Settings):Promise<void>;
