// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFmpegInstalled() {
  return window['go']['main']['App']['CheckFFmpegInstalled']();
}

export function Cleanup() {
  return window['go']['main']['App']['Cleanup']();
}

export function ClearAudioCache() {
  return window['go']['main']['App']['ClearAudioCache']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCacheInfo() {
  return window['go']['main']['App']['GetCacheInfo']();
}

export function GetCoverServerInfo() {
  return window['go']['main']['App']['GetCoverServerInfo']();
}

export function GetDiscordRPCStatus() {
  return window['go']['main']['App']['GetDiscordRPCStatus']();
}

export function GetPlaylists() {
  return window['go']['main']['App']['GetPlaylists']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSongFile(arg1) {
  return window['go']['main']['App']['GetSongFile'](arg1);
}

export function GetSongFileURL(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSongFileURL'](arg1, arg2, arg3);
}

export function GetStaticFolderPath() {
  return window['go']['main']['App']['GetStaticFolderPath']();
}

export function NotifyPlaybackState(arg1, arg2) {
  return window['go']['main']['App']['NotifyPlaybackState'](arg1, arg2);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function ScanPlaylistFiles(arg1) {
  return window['go']['main']['App']['ScanPlaylistFiles'](arg1);
}

export function SetCurrentSong(arg1, arg2) {
  return window['go']['main']['App']['SetCurrentSong'](arg1, arg2);
}

export function TestDiscordRPC() {
  return window['go']['main']['App']['TestDiscordRPC']();
}

export function UpdateDiscordPresence(arg1, arg2) {
  return window['go']['main']['App']['UpdateDiscordPresence'](arg1, arg2);
}

export function UpdateDiscordPresenceWithPosition(arg1) {
  return window['go']['main']['App']['UpdateDiscordPresenceWithPosition'](arg1);
}

export function UpdatePlaybackPosition(arg1) {
  return window['go']['main']['App']['UpdatePlaybackPosition'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
